export const HomepageSliderImage = '/media/img/stock/banner.png'
export const BannerImage = '/media/img/stock/banner.png'
export const BannerImageIcon = '/media/svg/group-7.svg'
export const BannerImageArchitecture = '/media/svg/group-9.svg'
export const BannerImageBg = '/media/svg/bg.svg'
export const HomeShield = '/media/svg/shield-user.svg'
export const BuildingCoins = '/media/svg/building-coins.svg'
export const FileListShield = '/media/svg/file-list-shield.svg'
export const HeaderLogo = '/media/svg/header-logo.svg'
export const HeaderSearch = '/media/svg/search-icon.svg'
export const WhySwoosh = '/media/svg/why_swoosh.svg'
export const HomeCard1 = '/media/svg/homecard1.svg'
export const HomeCard2 = '/media/svg/homecard2.svg'
export const HomeCard3 = '/media/svg/homecard3.svg'
export const HomeCard4 = '/media/svg/homecard4.svg'
export const HomeDesign = '/media/svg/Vector.svg'
export const RightArrowWhite = '/media/svg/right_arrow.svg'
export const RightArrowPimary = '/media/svg/icon_2.svg'
export const AIBackGroundImage = '/media/img/stock/group-1000001962.png'
export const MaskGroup = '/media/svg/mask-group.svg'
export const MaskGroupDesign = '/media/svg/Abstract_network_connection 1.svg'
export const FooterScnxt = '/media/svg/Group 6089.svg'
export const WhySwooshLogo = '/media/svg/group-168342.svg'

// bazaar screens header
export const CancelIconInHeader = '/media/icons/duotone/general/cancel.svg'
export const SearchIconInHeader = '/media/icons/duotone/general/search.svg'

// bazaar screens
export const CardIcon = '/media/svg/b-card-icon.svg'
export const DetailedVideo = '/media/videos/demo.mp4'
export const RightArrowLink = '/media/svg/right_arrow.svg'

// pillars fo support
export const PillarsOfSupport1 = '/media/svg/pillarsofsupport/rectangle-37209@3x.png'
export const PillarsOfSupport2 = '/media/svg/pillarsofsupport/rectangle-37207@3x.png'
export const PillarsOfSupport3 = '/media/svg/pillarsofsupport/rectangle-37208@3x.png'
export const SCNXLogo = '/media/svg/pillarsofsupport/SCNXT_LOGO_1.svg'
export const Team = '/media/svg/pillarsofsupport/photo@3x.png'
export const Instagram = '/media/svg/pillarsofsupport/instagram.svg'
export const Twitter = '/media/svg/pillarsofsupport/twitter.svg'
export const Facebook = '/media/svg/pillarsofsupport/facebook.svg'
export const UseCasesImageBanner = '/media/svg/pillarsofsupport/facebook.svg'
export const Brain = '/media/svg/pillarsofsupport/brain.svg'
export const Database = '/media/svg/pillarsofsupport/database.svg'
export const BotIcon = '/media/svg/pillarsofsupport/Group_213.svg'
export const Airplay = '/media/svg/pillarsofsupport/airplay-alt.svg'
export const IconRight = '/media/svg/pillarsofsupport/Icon_2.svg'
export const IconLeft = '/media/svg/pillarsofsupport/Icon.svg'

// login
export const LoginBG = '/media/svg/login/Group_1.svg'

// Help or How to get Started
export const HelpBanner = '/media/svg/login/Group_1.svg'

// const Search1
export const SearchIconText = '/media/svg/help/search-text.svg'
export const SearchIconBlack = '/media/svg/help/buttons-icon-filled-resting-on-light.svg'
export const UseCaseSearchIcon = '/media/icons/duotone/general/search.svg'
export const Help1RightArrow = '/media/svg/help/arrow-duotone-black.svg'
export const Help1Banner = '/media/svg/help/nwdn-file-temp-1615097887533-1@3x.png'

// use cases detailed
export const CasesBanner = '/media/svg/usecases/banner@3x.png'
export const CasesFlag = '/media/svg/usecases/flag-triangle.svg'
export const CasesTarget = '/media/svg/usecases/target.svg'
export const CasesUser = '/media/svg/usecases/user-check-alt.svg'
export const CasesVideoButton = '/media/svg/usecases/toko-design-general-line-play.svg'

// ingestion xtract-cheque
export const XtractInfoIcon = '/media/svg/ingestion/info-circle.svg'
export const XtractBackArrow = '/media/svg/ingestion/Arrow_Button.svg'
export const XtractCancel = '/media/svg/ingestion/cancel_icon.svg'
export const XtractHomeIcon = '/media/svg/ingestion/home-roof-user.svg'
export const XtractUserImg = '/media/svg/ingestion/img.png'
export const XtractCompleteSign = '/media/svg/ingestion/Group_1.svg'
export const XtractPendingSign = '/media/svg/ingestion/Group_2.svg'
export const XtractFileUpload = '/media/svg/ingestion/file-upload.svg'
export const XtractListError = '/media/svg/ingestion/icon.svg'
export const XtractListReUpload = '/media/svg/ingestion/icon_5.svg'
export const XtractListReUploadCircle = '/media/svg/ingestion/Group_1000002062.svg'
export const XtractListComplete = '/media/svg/ingestion/icon_2.svg'
export const XtractListTrash = '/media/svg/ingestion/trash.svg'
export const XtractListHistory = '/media/svg/ingestion/history.svg'
export const XtractProceed = '/media/svg/ingestion/arrow-duotone-black.svg'
